Feature/gh 145
MauroDataMapper/mdm-ui pull request #168
Opened 2021-06-08 12:21 UTC by gammonpeter

2021-06-09 10:03 UTC, pjmonks requested changes
A lot of effort went into this, good work. I'm liking how the duplication of code is reducing now. 👍 

I have found a number of issues which I would like reviewed before I approve. The more significant issues are functional, I found a few bugs with editing/saving the values - maybe the appeared because of the complex rebase. The main bugs I found are centered around:

1. Validation - either some validation isn't run, or validation prevents saving but doesn't always show error messages for the user. Examples I've found are particularly around multiplicity controls.
2. Re-editing - edit the default profile and saving does re-render the read-only view. But editing the model again without a full refresh does not load the updated state back into the dialog.

2021-06-09 12:56 UTC, gammonpeter commented on src/app/classification/classification.component.ts
> +      resource[item.displayName.toLocaleLowerCase()] = item.value;
updated to use a property name

2021-06-09 13:46 UTC, gammonpeter commented on src/app/classification/classification.component.ts
> +        this.result.domainType = CatalogueItemDomainType.Classification;
No when i checked the result the domain isn't present

2021-06-09 15:01 UTC, gammonpeter commented on src/app/shared/default-profile/default-profile.component.ts
> +  @Input() catalogueItem: any;
i tried but a classifiers caused an issue so switched to any not idea i know

2021-06-09 15:02 UTC, gammonpeter commented on src/app/modals/default-profile-editor-modal/default-profile-editor-modal.component.ts
> +  fetchDataTypes = (text, loadAll, offset, limit) => {
this is being used another component so needs to be property syntax to allow it use editing service

2021-06-09 15:03 UTC, gammonpeter commented on src/app/modals/default-profile-editor-modal/default-profile-editor-modal.component.html
> +          <div *ngIf="item.controlType === profileControlType.multiplicity">
added TODO in ts file

2021-06-10 08:24 UTC, pjmonks commented on src/app/modals/default-profile-editor-modal/default-profile-editor-modal.component.ts
> +  fetchDataTypes = (text, loadAll, offset, limit) => {
OK, no problem with getting it to fit with existing code.

2021-06-10 08:25 UTC, pjmonks commented on src/app/shared/default-profile/default-profile.component.ts
> +  @Input() catalogueItem: any;
OK, if it works for now it's something that could be looked at later.

2021-06-10 08:55 UTC, pjmonks submitted a review, later dismissed
These current changes look good to me.

Found an issue during testing, the Edit Default Profile dialog can't open when requested. Also need to fix the Jenkins issues to get that passing.

2021-06-10 14:19 UTC, pjmonks approved these changes
I think you've nailed it 🥳

2021-06-10 14:20 UTC, merged