MC-9606
MauroDataMapper/mdm-ui pull request #396
Opened 2021-11-12 17:17 UTC by atpw25

2021-11-15 14:24 UTC, gammonpeter requested changes

2021-11-16 12:17 UTC, atpw25 commented
All changes have been committed.

2021-11-16 13:57 UTC, gammonpeter requested changes

2021-11-16 13:57 UTC, gammonpeter commented on src/app/term/codeset-list/term-codeset-list.component.html
> +    <mat-paginator [length]="totalItemCount" [pageSize]="pageSize" pageIndex="0" showFirstLastButtons></mat-paginator>
please use mdm-paginator as this handles user configs

2021-11-16 13:57 UTC, gammonpeter commented on src/app/term/codeset-list/term-codeset-list.component.ts
> +      offset: (this.paginator?.pageIndex * this.paginator?.pageSize) || 0
using mdm-paginator handles these calculations

2021-11-16 13:57 UTC, gammonpeter commented on src/app/terminology/term-list/term-list.component.html
> +    <mat-paginator [length]="totalItemCount" [pageSize]="pageSize" pageIndex="0" showFirstLastButtons></mat-paginator>
switch to using mdm-paginator

2021-11-16 15:09 UTC, gammonpeter approved these changes

2021-11-16 15:13 UTC, merged