#464 Use content editor for description fields in "New..." wizards
MauroDataMapper/mdm-ui pull request #486
Opened 2022-03-03 16:29 UTC by pjmonks

Resolves #464 

![image](https://user-images.githubusercontent.com/3219480/156607947-ec86a394-4720-41dd-afdb-87aeec657255.png)

2022-03-03 16:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MauroDataMapper/mdm-ui?pullRequest=486) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MauroDataMapper/mdm-ui?pullRequest=486) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MauroDataMapper/mdm-ui?pullRequest=486) it.</sub>

2022-03-07 13:49 UTC, jamesrwelch requested changes
Minor change - I thin it needs the word 'description' somewhere so we can see which field is being edited.

2022-03-08 17:11 UTC, pjmonks commented
I've tried to add labels above the description content editors now, which look like this:

![image](https://user-images.githubusercontent.com/3219480/157289366-4bbf3886-c202-4929-a77a-9bd6ceee4aa5.png)

They don't look consistent with the other Angular Material fields because they are not wrapped in a `mat-form-field` component - they can't be, because these custom editors have not been configured to be allowed as child components. I've tried to replicate the style of these labels as best I can for now instead.

2022-03-13 22:00 UTC, jamesrwelch approved these changes
Yes, this is great, thanks :)

2022-03-13 22:00 UTC, merged