Subscribed Catalogue changes to support multiple Authentication Types
MauroDataMapper/mdm-ui pull request #737
Opened 2023-01-24 15:48 UTC by joe-crawford

- Display versions (or model version tags) for Published Models in the tree entry for a Subscribed Catalogue.
- In the Subscribed Catalogue admin settings page, add fields to choose Authentication Type and required authentication fields for each type (No Authentication, API Key or OAuth (Client Credentials)).

Depends on https://github.com/MauroDataMapper/mdm-resources/pull/84.

2023-01-24 15:53 UTC, joe-crawford commented
Screenshots after changes:

Subscribed Catalogues list in Admin Settings (`/admin/subscribedCatalogues`):
<img width="1286" alt="Screenshot 2023-01-24 at 15 50 54" src="https://user-images.githubusercontent.com/33897179/214341591-609d1630-25e0-4859-bc94-adb6626249b9.png">

Subscribed Catalogue entry/update page (`/admin/subscribedCatalogue/{{id}}`):
<img width="827" alt="Screenshot 2023-01-24 at 15 50 08" src="https://user-images.githubusercontent.com/33897179/214341814-c722ed3a-6ccb-4e58-a002-71a822dcef10.png">

Subscribed Catalogue tree view:
<img width="662" alt="Screenshot 2023-01-24 at 15 53 19" src="https://user-images.githubusercontent.com/33897179/214341979-5a7d45b3-15d8-4d5d-b1a3-e9005788a07c.png">
...

2023-01-27 12:38 UTC, jamesrwelch commented
One typescript error, and a couple of minor issues after merging and upgrading to latest Typescript.  I'm happy to take a look myself and fix before accepting

2023-02-01 06:44 UTC, jamesrwelch requested changes
This all seems to work well, and the tests pass and the linting succeeds - good job!  One minor change, please - the styling of the hint "The syndication feed URL to connect to" makes it unclear where the hint should go, or what it relates to.  Are you able to add some spacing or something?  This may be a more general problem with hints that we should resolve globally at a later date.
<img width="614" alt="Screenshot 2023-02-01 at 06 41 46" src="https://user-images.githubusercontent.com/1869668/215970815-8992b1ab-21b6-44c0-82d2-6934faa1def2.png">

2023-02-03 19:37 UTC, jamesrwelch approved these changes
Looks much better, works much better.  Great work!

2023-02-03 19:39 UTC, jamesrwelch commented
@joe-crawford Not sure what's going on with the conflicts though 😕

2023-02-03 19:47 UTC, joe-crawford commented
@jamesrwelch sorry I have a fix for this but the commit is not finished yet :)


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: James Welch ***@***.***>
Sent: Friday, February 3, 2023 7:39:59 PM
To: MauroDataMapper/mdm-ui ***@***.***>
Cc: Joe Crawford ***@***.***>; Mention ***@***.***>
Subject: Re: [MauroDataMapper/mdm-ui] Subscribed Catalogue changes to support multiple Authentication Types (PR #737)


@joe-crawford<https://github.com/joe-crawford> Not sure what's going on with the conflicts though 😕

—
Reply to this email directly, view it on GitHub<https://github.com/MauroDataMapper/mdm-ui/pull/737#issuecomment-1416321322>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AICTVW7UO4FA7ULGGROFGVDWVVNI7ANCNFSM6AAAAAAUFH7VQU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-02-06 21:08 UTC, joe-crawford commented
Latest commit has a rebase and adds some padding to the field captions, and fixes an issue with the required field validation when toggling between different authentication types.

2023-02-07 08:21 UTC, jamesrwelch approved these changes
Really great piece of work - nice one!

2023-02-07 08:21 UTC, merged